import { Info, Plus } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useChatStore } from "@/lib/chat-store";
import { STARTERS } from "@/lib/starters";
import { Button } from "@/components/ui/button";
import { Composer } from "@/components/chat/composer";
import { MessageList } from "@/components/chat/message-list";
import { Portrait } from "@/components/chat/portrait";
import { ProfilePanel } from "@/components/chat/profile-panel";

export function ChatApp(){const messages=useChatStore(s=>s.messages),add=useChatStore(s=>s.addMessage),append=useChatStore(s=>s.appendTo),setContent=useChatStore(s=>s.setContent),clear=useChatStore(s=>s.clear);const [streaming,setStreaming]=useState(false),[profile,setProfile]=useState(false),[error,setError]=useState<string|null>(null);const abortRef=useRef<AbortController|null>(null);useEffect(()=>()=>abortRef.current?.abort(),[]);
async function send(text:string){if(streaming||!text.trim())return;setError(null);setProfile(false);const user={id:crypto.randomUUID(),role:"user" as const,content:text.trim().slice(0,1400),createdAt:Date.now()},assistantId=crypto.randomUUID(),prior=useChatStore.getState().messages;add(user);add({id:assistantId,role:"assistant",content:"",createdAt:Date.now()});const controller=new AbortController();abortRef.current=controller;setStreaming(true);try{const res=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:[...prior,user].slice(-24)}),signal:controller.signal});if(!res.ok||!res.body){setContent(assistantId,res.status===503?"I’m offline right now. Try again when the connection is back.":res.status===429?"Too many people in my DMs at once. Give it a second.":"Something glitched on my end. Try again.");return}const reader=res.body.getReader(),decoder=new TextDecoder();let buffer="",assembled="";while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const lines=buffer.split("\n");buffer=lines.pop()??"";for(const line of lines){const t=line.trim();if(!t.startsWith("data:"))continue;const data=t.slice(5).trim();if(!data||data==="[DONE]")continue;try{const p=JSON.parse(data) as {delta?:string;error?:string};if(p.error){setContent(assistantId,assembled||"Something glitched on my end. Say that again.");return}if(p.delta){assembled+=p.delta;append(assistantId,p.delta)}}catch{}}}if(!assembled)setContent(assistantId,"I started typing and then didn't. Weird.")}catch(e){if((e as {name?:string}).name!=="AbortError"){setContent(assistantId,"Signal died. Send it once more.");setError("Couldn't reach her. Try again.")}}finally{setStreaming(false);abortRef.current=null}}
const empty=messages.length===0;return <div className="flex h-dvh min-h-0 bg-bg text-fg"><div className="grain"/><ProfilePanel onStarter={send} className="hidden w-[22rem] shrink-0 border-r border-border lg:flex"/><main className="flex min-w-0 flex-1 flex-col"><header className="flex h-16 shrink-0 items-center gap-3 border-b border-border px-4 sm:px-6"><button onClick={()=>setProfile(true)} className="flex min-w-0 items-center gap-3 rounded-lg py-1 pr-2 text-left"><span className="relative"><Portrait size="md"/><span className="absolute right-0 bottom-0 size-2.5 rounded-full border-2 border-bg bg-online"/></span><span><span className="block text-sm font-medium">Sarah Joe</span><span className="block text-xs text-muted">AI portrayal</span></span></button><div className="ml-auto flex gap-1"><Button variant="ghost" size="icon" className="lg:hidden" onClick={()=>setProfile(true)} aria-label="Profile"><Info className="size-5"/></Button><Button variant="ghost" size="icon" onClick={()=>{abortRef.current?.abort();clear();setError(null)}} aria-label="New chat"><Plus className="size-5"/></Button></div></header><div className="min-h-0 flex-1 overflow-y-auto">{empty?<EmptyState onStarter={send}/>:<MessageList messages={messages} streaming={streaming}/>}</div>{error&&<p className="px-6 pb-1 text-center text-xs text-danger">{error}</p>}<Composer streaming={streaming} onSend={send} onStop={()=>abortRef.current?.abort()}/></main>{profile&&<div className="fixed inset-0 z-40 lg:hidden"><button className="absolute inset-0 bg-bg/70" onClick={()=>setProfile(false)} aria-label="Dismiss"/><div className="absolute inset-y-0 left-0 w-[min(100%,24rem)] shadow-soft"><ProfilePanel onStarter={send} onClose={()=>setProfile(false)}/></div></div>}</div>}
function EmptyState({onStarter}:{onStarter:(text:string)=>void}){return <div className="mx-auto flex min-h-full w-full max-w-2xl flex-col justify-center px-4 py-12 sm:px-6"><div className="mb-8 flex items-center gap-4"><Portrait size="lg"/><div><p className="text-xs tracking-[.18em] text-subtle uppercase">Direct message</p><h1 className="font-display text-4xl">Sarah Joe</h1><p className="mt-1 text-sm text-muted">fictionalized public-persona portrayal</p></div></div><div className="grid gap-2 sm:grid-cols-2">{STARTERS.map(s=><Button key={s.label} variant="quiet" className="h-auto justify-start rounded-xl px-4 py-3 text-left font-normal" onClick={()=>onStarter(s.text)}><span><span className="block text-xs text-muted">{s.label}</span><span className="text-sm">{s.text}</span></span></Button>)}</div></div>}
